### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by renehauck** [pipech/erpnext-docker-debian#100]
Hi first of all many thanks for the work! 
Now for my problem: I start erpnext, as in your documentation, with the command 
`docker run -d -p 8000:8000 -p 9000:9000 -p 3306:3306 pipech/erpnext-docker-debian:mas-py3-latest`.
 Everything works fine, but when I try to create a resource using the RestApi, I get an error message:

```
Traceback (most recent call last):
  File "/home/frappe/bench/apps/frappe/frappe/app.py", line 58, in application
    init_request(request)
  File "/home/frappe/bench/apps/frappe/frappe/app.py", line 118, in init_request
    make_form_dict(request)
  File "/home/frappe/bench/apps/frappe/frappe/app.py", line 126, in make_form_dict
    args = json.loads(request.data)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

This problem has been discussed here before: https://discuss.erpnext.com/t/bug-frappe-api-encoding-case-typeerror-the-json-object-must-be-str/40359/9

The solution was to use python 3.6. Do the docker files need to be updated or am I doing something wrong? :smiley:

**Comment by pipech** [comment]
Hello,

I think you should try newer tag image such as `v12-py3-latest` or `12-F8.4_E10.1-py3`
`mas-py3-latest` is quite old image and I'll update the wiki page.

Thank you!

**Comment by pipech** [comment]
Could you try again with `12-F8.4_E10.1-py3` tags ?
I've check it use python version 3.7

**Comment by pipech** [comment]
`mas-py3-latest` is an old version tag, I believed it's version 11.

Using newer image tag such as `12-F8.4_E10.1-py3` or `v12-py3-latest` should solve your problem.
