### ISSUE TITLE
How to connect to database with MysqlWorkbench

### ISSUE THREAD

**Issue by shuairobin** [pipech/erpnext-docker-debian#101]
Trial Setup
How to connect to database with MysqlWorkbench

**Comment by pipech** [comment]
Use these credentials

Hostname : localhost
Port : 3306
User : remote
Pass : 12345

**Comment by shuairobin** [comment]
Failed to Connect to MySQL at localhost:3306 with user remote
Access denied for user 'remote'@'172.17.0.1'(using password:YES)

**Comment by shuairobin** [comment]
![mysqlworkbench](https://user-images.githubusercontent.com/19880280/91022498-e21ebe00-e627-11ea-9d03-c214ca1a0331.png)

**Comment by shuairobin** [comment]
![dockerps-a](https://user-images.githubusercontent.com/19880280/91022531-ec40bc80-e627-11ea-9406-ca0985fc4089.png)
