### ISSUE TITLE
I use Hostname : localhost connect databases;

### ISSUE THREAD

**Issue by shuairobin** [pipech/erpnext-docker-debian#102]
I 
![mysqlworkbench](https://user-images.githubusercontent.com/19880280/91026788-d0401980-e62d-11ea-9e34-aa2faa99ed55.png)
![dockerps-a](https://user-images.githubusercontent.com/19880280/91026794-d2a27380-e62d-11ea-9e3a-0b332018e6fd.png)

I use Hostname : localhost
Port : 3306
User : remote
Pass : 12345

**Comment by pipech** [comment]
Could you try

```
Hostname : localhost
Port : 3306
User : root
Pass : 12345
```

**Comment by shuairobin** [comment]
No command line in Docker, the system can log in.
![mysql](https://user-images.githubusercontent.com/19880280/91110573-cad7e300-e6b0-11ea-8a07-4e1a9f9c7189.png)

**Comment by pipech** [comment]
https://github.com/pipech/erpnext-docker-debian/issues/106
