### ISSUE TITLE
External database

### ISSUE THREAD

**Issue by renehauck** [pipech/erpnext-docker-debian#107]
Hi,

Is there a possibility/version where an external MariaDB and/or an external Redis server can be used. So that I can enter the host of both and they won't be started as a service in the container? 

Thx for your help!

**Comment by pipech** [comment]
Sorry for really late reply.

I guess you mean you want to use redis and mariadb from host not from container.
You could config it in [common_site_config_docker.json](https://github.com/pipech/erpnext-docker-debian/blob/master/production_setup/conf/frappe-docker-conf/common_site_config_docker.json)

On db_host, redis_cache, redis_queue, redis_socketio.

```json
{
 "auto_update": false,
 "background_workers": 1,
 "dns_multitenant": true,
 "db_host": "mariadb",
 "file_watcher_port": 6787,
 "frappe_user": "frappe",
 "gunicorn_workers": 4,
 "rebase_on_pull": false,
 "redis_cache": "redis://redis-cache:13000",
 "redis_queue": "redis://redis-queue:11000",
 "redis_socketio": "redis://redis-socketio:12000",
 "restart_supervisor_on_update": false,
 "root_password": "123",
 "serve_default_site": true,
 "shallow_clone": true,
 "socketio_port": 9000,
 "update_bench_on_update": true,
 "admin_password": "admin"
}
```

Will close this issues for now feel free to re-open.
