### ISSUE TITLE
setup wizard failing / worker timeout / supervisorctl no socket found

### ISSUE THREAD

**Issue by H0ST4L3X** [pipech/erpnext-docker-debian#108]
Spent the whole day trying to resolve this issue:

Up until the setup wizard everything runs fine.
The setup wizard will not complete due to a `Request Timed Out`.
Inside the frappe docker container the log `logs/web.error.log` says:
```
[2020-10-19 17:59:58 +0000] [29] [INFO] Starting gunicorn 19.10.0
[2020-10-19 17:59:58 +0000] [29] [INFO] Listening at: http://0.0.0.0:8000 (29)
[2020-10-19 17:59:58 +0000] [29] [INFO] Using worker: sync
[2020-10-19 17:59:58 +0000] [70] [INFO] Booting worker with pid: 70
[2020-10-19 17:59:58 +0000] [71] [INFO] Booting worker with pid: 71
[2020-10-19 17:59:58 +0000] [72] [INFO] Booting worker with pid: 72
[2020-10-19 17:59:58 +0000] [73] [INFO] Booting worker with pid: 73
[2020-10-19 18:03:51 +0000] [29] [CRITICAL] WORKER TIMEOUT (pid:72)
[2020-10-19 18:03:52 +0000] [217] [INFO] Booting worker with pid: 217
```

I have set the timeout for the supervisor.conf to `300` in all of these places:

inside the frappe container:
`/home/frappe/bench/sites/common_site_config.json`
`/etc/supervisor/conf.d/supervisor.conf`

on the docker host:
`~/erpnext-docker-debian/production_setup/conf/frappe-docker-conf/supervisor.conf`

and in a few other files I don't remember atm.

I also tried to set the nginx `proxy_read_timeout` to `300` in the docker host and inside the container.

The frappe bench wiki says for setting the HTTP timeout one must issue these commands (in the frappe container):
```
bench config http_timeout 300
bench setup supervisor
bench setup nginx
```
Restart services (as root)
```
supervisorctl reload
service nginx reload
```
source: https://github.com/frappe/bench/wiki/Setting-HTTP-timeout

In other threads I have read that one might also want to link the supervisor.conf and nginx.conf to the ones in /etcsupervisor/conf.d/… and in /etc/nginx/…

Anyways, reloading the supervisor via `sudo supervisorctl reload` fails with:
```
frappe@6305b23dec7c:~/bench$ sudo supervisorctl reload
error: <class 'socket.error'>, [Errno 2] No such file or directory: file: /usr/lib/python2.7/socket.py line: 228
```
with and without sudo.

Actually I tried to set the timeout to 300 in literally every file, in the docker host's erpnext-docker-debian dir before setting everything up, later in the docker container, just everywhere where I could grep through.

When I look at the running processes I see:
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
frappe       1  0.0  0.0   6660  3252 pts/0    Ss+  17:59   0:00 /bin/bash /home/frappe/production_config/entrypoint_prd.sh
root        15  0.0  0.0  69864  1772 ?        Ss   17:59   0:00 nginx: master process nginx
www-data    16  0.0  0.1  70768  7316 ?        S    17:59   0:00 nginx: worker process
www-data    17  0.0  0.1  70768  7312 ?        S    17:59   0:00 nginx: worker process
www-data    18  0.0  0.1  70768  7336 ?        S    17:59   0:00 nginx: worker process
www-data    19  0.0  0.1  70768  7308 ?        S    17:59   0:00 nginx: worker process
root        20  0.0  0.1  10152  4040 pts/0    S+   17:59   0:00 sudo /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisor.conf
root        21  0.1  0.5  26732 20500 pts/0    S+   17:59   0:01 /usr/bin/python2 /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisor.conf
frappe      24  2.1  1.8 152312 73776 pts/0    S    17:59   0:19 /home/frappe/bench/env/bin/python -m frappe.utils.bench_helper frappe schedule
frappe      25  0.9  1.5 103072 60536 pts/0    S    17:59   0:08 /home/frappe/bench/env/bin/python -m frappe.utils.bench_helper frappe worker --queue default
frappe      26  0.8  1.4 101996 59916 pts/0    S    17:59   0:07 /home/frappe/bench/env/bin/python -m frappe.utils.bench_helper frappe worker --queue long
frappe      27  0.7  1.4 101884 59800 pts/0    S    17:59   0:06 /home/frappe/bench/env/bin/python -m frappe.utils.bench_helper frappe worker --queue short
frappe      28  0.2  1.4 866884 59048 pts/0    Sl   17:59   0:02 /usr/bin/node /home/frappe/bench/apps/frappe/socketio.js
frappe      29  0.5  1.7 150376 71296 pts/0    S    17:59   0:05 /home/frappe/bench/env/bin/python3 /home/frappe/bench/env/bin/gunicorn -b 0.0.0.0:8000 -w 4 -t 120 frappe.app:application --preload
frappe      70  0.2  2.1 175464 86804 pts/0    S    17:59   0:02 /home/frappe/bench/env/bin/python3 /home/frappe/bench/env/bin/gunicorn -b 0.0.0.0:8000 -w 4 -t 120 frappe.app:application --preload
frappe      71  0.4  1.8 164052 76156 pts/0    S    17:59   0:04 /home/frappe/bench/env/bin/python3 /home/frappe/bench/env/bin/gunicorn -b 0.0.0.0:8000 -w 4 -t 120 frappe.app:application --preload
frappe      73  0.4  2.3 181372 93780 pts/0    S    17:59   0:04 /home/frappe/bench/env/bin/python3 /home/frappe/bench/env/bin/gunicorn -b 0.0.0.0:8000 -w 4 -t 120 frappe.app:application --preload
frappe     217  0.0  1.5 152356 61212 pts/0    S    18:03   0:00 /home/frappe/bench/env/bin/python3 /home/frappe/bench/env/bin/gunicorn -b 0.0.0.0:8000 -w 4 -t 120 frappe.app:application --preload
frappe     251  0.0  0.0   6924  3624 pts/1    Ss   18:12   0:00 bash
frappe     323  0.0  0.0  10848  3168 pts/1    R+   18:15   0:00 ps -aux
```

I see the four workers:
`/home/frappe/bench/env/bin/python3 /home/frappe/bench/env/bin/gunicorn -b 0.0.0.0:8000 -w 4 -t 120 frappe.app:application --preload`
… and I have no idea where they get that timeout of 120 from, while everywhere it is set to 300.

There is two supervisor processes, one is started via python2 binary?

Also I have no idea how to interactively enter the or one of the two supervisor processes successfully to make it reload the configuration. Alwas get the socket error.

Entering the virtual environment does not help either.

`bench restart` or `bench update` does not get me anywhere either.

Updating the stack just resets everything to default.

I have tried these two tags:
`v12-py3-latest` and `13-Fx200922-py3`, both fail.

The system is a vServer with 4 vCores, 80 GB SAS and 4 GB DDR 3 ECC RAM.
I managed to get the setup done in a smaller vServer some long time ago without troubles…

It's been a very frustrating day.

Please someone help out.

**Comment by pipech** [comment]
Hi,

The minimal requirement is 4GB of ram but you should try to set it to 8GB of ram and see if that helps because there might be another service using those ram.

**Comment by H0ST4L3X** [comment]
Hi @pipech
set it up on my own server with plenty of headroom, works fine of course. It used around 6.2 GB RAM.
Still I wonder: How do you change the settings for the gunicorn workers, i.e. the timeout setting? Where do the workers get their settings from?

**Comment by H0ST4L3X** [comment]
OK, so it worked out finally.
In case anyone stumbles upon this issue, here is how to resolve it.
Please refer also to this thread discuss.erpnext.com which had the solution ready:
[Gunicorn Worker how to increase](https://discuss.erpnext.com/t/gunicorn-worker-how-to-increase/28349/9)

- Follow the instructions as per the Wiki.
- Before logging in for the first time change the worker timeout as follows:
1. On the docker host execute:
`docker exec -it <frappe_container_id> bash`
2. In the container execute:
sudo nano /etc/supervisor/conf.d/supervisor.conf
Change the parameters for worker count and timeout as per your server resources. In my case on a vServer with 6vCores and ~8GB RAM I use 6 workers and a timeout of 5 minutes:
`command=/home/frappe/bench/env/bin/gunicorn -b 0.0.0.0:8000 -w 6 -t 300 frappe.app:application --preload`
3. Find a way to restart/reload the supervisor process. I used `sudo htop`, `F9` and sent the supervisord process a SIGHUP hang-up signal. That restarts the supervisor and creates 6 workers with a timeout of 300 seconds.
- Finally follow the web GUI to set up your _company_.

Changes to the supervisor conf / workers will not be persistent through stack updates.
