### ISSUE TITLE
How to Add OpenSSL or letsencrypt SSL for Production Docker URL

### ISSUE THREAD

**Issue by shrikant9867** [pipech/erpnext-docker-debian#109]
As per checking all method, I'm not able to add free SSL to URL/site which is hosted inside docker,
can u pls help to understand above concept

**Comment by pipech** [comment]
Sorry for late reply, SSL will be add by traefik container.

[https://github.com/pipech/erpnext-docker-debian/wiki/Production-Setup](https://github.com/pipech/erpnext-docker-debian/wiki/Production-Setup)

You will have to config email on `production_setup/conf/traefik-conf/traefik.toml` file.

Feel free to re-open this issues if needed.

**Comment by RashiqAzhan** [comment]
I am getting a "CA Root Certificate not trusted" error. Am I missing something?
