### ISSUE TITLE
Two bugs: list.min.css 404 and Port 9000 on /socket.io/?EIO=3

### ISSUE THREAD

**Issue by takyeyu** [pipech/erpnext-docker-debian#110]
I installed the 13-Fx210302-py3 images, while I found that there are two issues,

1. missing file list.min.css in desk view, no need to build list.min.css in build.json, but the page will include list.min.css, so it caused 404 of this file
2. every 10 second, I will got an error "GET https://xxxx.com:9000/socket.io/?EIO=3&transport=polling&t=" in google console, I know it is about port of socket.io, how can I make system to run this link without the port 9000, I tried this link, but can't fixed https://discuss.erpnext.com/t/error-in-console-net-err-connection-refused/29046

Could anyone guide me to fixed these two problems, thanks
![WechatIMG64](https://user-images.githubusercontent.com/11435182/111895081-09692c80-8a4b-11eb-8034-e348cc40480b.jpeg)

**Comment by pipech** [comment]
Sorry for late reply,

Are you running from production setup config? You shouldn't getting port 9000 error.

**Comment by takyeyu** [comment]
> Sorry for late reply,
> 
> Are you running from production setup config? You shouldn't getting port 9000 error.

Hi Pipech, sorry for late reply, bench update will fix css error, and for the port 9000, as I install it through plesk UI, seem I can only run trial setup, may I know if there is any guide, so I can run the production setup or change the trial version to production, thank you very much for your kind advice in advanced
