### ISSUE TITLE
ERPNEXT 14

### ISSUE THREAD

**Issue by Airbrando** [pipech/erpnext-docker-debian#124]
Hello,
is there any chance that your Docker Version V13 will be upgradeable to version 14 ? If i do this manually per Terminal i get an error. Can you please help ?!
Thank in advance
Christoph

**Comment by aakhanfar** [comment]
I think the problem is that the image is based on debian 10, and that comes shipped with python 3.7.
Try building it with debian 11. I think it's a problem with the python version, please tell me if it works for you.
