### ISSUE TITLE
frappe init.sh fails on mv

### ISSUE THREAD

**Issue by pradeshc** [pipech/erpnext-docker-debian#18]
When I run the ./init.sh script, the mv fails

```
. init.sh
++ sudo mv ./sites-dev/apps.txt ./sites-dev/assets ./sites-dev/common_site_config.json ./sites-dev/currentsite.txt ./sites-dev/site1.local ./sites/
mv: will not create hard link './sites/site1.local/locks' to directory './sites/assets'
```

**Comment by pipech** [comment]
Hi,
What is your docker version ?
What erpnext-docker-debain tag are you using ?

Could you try to use older version, ie v10.1.40 or v10.1.37 ?

**Comment by pradeshc** [comment]
I found a workaround.

I ssh into my frappe container

`$ docker exec -it 9a0bc6603953  bash`

Then edit the init.sh file and replace the mv with a cp -r (I used vi)


```
#!/bin/bash

# turn on debug mode > https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -euxo pipefail

# change sites and apps folder to it's original folder
# sudo mv  ./sites-dev/* ./sites/
sudo cp -r ./sites-dev/* ./sites/
sudo rm -rf ./sites-dev/
# sudo mv  ./apps-dev/* ./apps/
sudo cp -r  ./apps-dev/* ./apps/
sudo rm -rf ./apps-dev/

#   ...
```

FYI, the docker version is 1.12.0 (on Ubuntu 16.04 LTS), using the **development_setup**.
