### ISSUE TITLE
Import Not Working

### ISSUE THREAD

**Issue by Olawale1** [pipech/erpnext-docker-debian#21]
Hi @pipech 

Trust you're doing great. It seems like the **Data Import** feature isn't working in this setup. Once I click on 'Start Import', the status changes to 'Failed'

Please advise

Thanks

**Comment by pipech** [comment]
Hi,

I not sure if it relate to this setup, could you please share you error message.
There should be an error message on the top right side of erpnext (the red notification things).

Regards

**Comment by Olawale1** [comment]
Hi @pipech 

You're absolutely right! It was because of an error in the format of one of the fields. I'm however wondering why the error message didn't pop up on the screen and didn't even show in the console!

Thanks for pointing me to the error log

Kind regards,
