### ISSUE TITLE
Default Email Templates use {{ link }} that pulls container port 8000 causing unreachable link

### ISSUE THREAD

**Issue by stapeldev** [pipech/erpnext-docker-debian#38]
Forgive me if this has already been addressed. For the automated emails, such as password reset, invites, etc. in ERPNext, the links that get sent by default are generating using the container port of 8000. For example http://my.erpnext.com:8000/resetmypassword/etc.

This causes the link to be unreachable because Traefik is not exposing 8000 as an entrypoint. Any recommendations on how to resolve this issue? Or did I miss something in the instructions? Thanks in advance. 

***Perhaps adding entrypoints for default Erpnext port and redirecting to https in Traefik config file.

**Comment by pipech** [comment]
Production setup is suppose to run on port 80, so it shouldn't have this problem.

Did you run production setup on port 8000 or you run development setup with traefik ??

Anyways you should check the instruction or you could share your config here.

**Comment by stapeldev** [comment]
Pipech, thanks for the reply. I am pretty sure I ran the production setup.  And it's entirely possible I am misunderstanding what is happening here. I think the issue is that the container is using the web server port in the settings found in the common_site_config file found here:  https://github.com/pipech/erpnext-docker-debian/blob/master/production_setup/conf/frappe-docker-conf/common_site_config_docker.json 

Here's the service config from the prd.yml:

frappe:
    image: pipech/erpnext-docker-debian:11.1.4-py3
    deploy:
      replicas: 1
    volumes:
      - frappe-sites-volumes:/home/frappe/bench/sites
      - frappe-logs-volumes:/home/frappe/bench/logs
    stdin_open: true
    tty: true
    env_file:
      - ./env/frappe_app.env
    command: ["/home/frappe/production_config/entrypoint_prd.sh"]
    labels:
      - "traefik.enable=true"
      # - "traefik.frontend.rule=Host:example1.com, example2.com" [Separate with comma]
      - "traefik.frontend.rule=Host:my.host.name"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_proxy"
    networks:
      - traefik_proxy
      - default

Common Site Config:
{
 "auto_update": false,
 "background_workers": 1,
 "dns_multitenant": true,
 "db_host": "mariadb",
 "file_watcher_port": 6787,
 "frappe_user": "frappe",
 "gunicorn_workers": 4,
 "rebase_on_pull": false,
 "redis_cache": "redis://redis-cache:13000",
 "redis_queue": "redis://redis-queue:11000",
 "redis_socketio": "redis://redis-socketio:12000",
 "restart_supervisor_on_update": false,
 "root_password": "123",
 "serve_default_site": true,
 "shallow_clone": true,
 "socketio_port": 9000,
 "update_bench_on_update": true,
 "webserver_port": 8000,
 "admin_password": "admin"
}

Found the following old issue, which seemed similar:  https://discuss.erpnext.com/t/incorrect-erpnext-hosting-links-in-sent-emails/154/2 where it was suggested to put a "host_name" value in the specific site config file.  I did that on my site and it seems to have fixed the issue. Not sure if this is a good solution though.  Perhaps you can point me to the specific config that I should be looking at in the production setup? Sorry for my lack of understanding on this. Very new to ERP and Docker.  Here's the specific setting that was added, in case someone else runs into this:

bench/sites/my.site.name/site_config.json added: "host_name": "http://my.host.name:80", right underneath the encryption key, so it looks like this:

{
 "db_name": "somedbname",
 "db_password": "somedbpassword",
 "encryption_key": "somereallylongencryptionkey",
 "host_name": "http://my.host.name:80",
 "limits": {
  "space_usage": {
   "backup_size": 1.0,
   "database_size": 25.72,
   "files_size": 14.0,
   "total": 40.72
  }
 }

This seems to solve the issue, because now the links in the default emails are overidden and Traefik handles them properly.  Any other thoughts would be helpful And thanks again.

**Comment by pipech** [comment]
That's odds, I'm using the same site config with webserver_port: 8000 but it doesn't have the problem.

Can you access your website via http://my.host.name or https://my.host.name ?

**Comment by stapeldev** [comment]
Sorry for the late reply. Yes http properly redirects to https and the side loads fine. I do have a few issues here and there, like slideshow problems and the letterhead images don’t seem to want to print. But I think that may be related to something different.

**Comment by stapeldev** [comment]
@pipech, thanks for your assistance and patience. I re-verified my configuration settings with the instructions in the Production Setup.  Regarding this variable {{ link }} in ERPNext I cannot determine why the default url is being generated with port 8000.  I do know, however, that adding the "host_name" setting in the site config resolves the issue for me.  I know that's not satisfactory in terms of knowing why it's not working in my instance, so I do apologize for any waste of your time.  Thanks again for your assistance.

**Comment by pipech** [comment]
It's my pleasure.
Did you tried ~~change "webserver_port" on common_site config to 80~~ deleting "webserver_port" line on common_site config, I really think it should solve this probelm. (You have to remove host_name in site config first)

According to [frappe.utils.data.get_url](https://github.com/frappe/frappe/blob/eead6809e104b8e4770ec7798299935d963179bb/frappe/utils/data.py#L689-L734) if the script didn't find any port setting it won't add any port to url.

**Comment by stapeldev** [comment]
I did not attempt that, thank you for pointing to this. I will attempt that later today. I Will update you most likely this evening. Thanks again!!

**Comment by stapeldev** [comment]
@pipech removing the "host_name" from the site_config.json in the bench/sites/my.site.name folder and then removing the "webserver_port" line in the common_site_config.json inside the bench/sites folder appears to address the issue.  The links sent by the system now arrive with just the site name and work great. Thanks for sticking with me on this one. Learning quite a bit.

**Comment by pipech** [comment]
Fixed: https://github.com/pipech/erpnext-docker-debian/commit/2a4d13ab30cb0ab3145c4b9547bccb342185d1cd

**Comment by k5672** [comment]
I followed your instructions in ERPNext v14 and well, instead of the ":8000" the URL gets generated with ":None" and looks like this:
"http://www.example.com/:None/app?sid=321e1ac24de8439b3c1624e2b47243eb6cd55b29"

Is it possible to remove the ":None" aswell ?
