### ISSUE TITLE
Can't find frappe container ID

### ISSUE THREAD

**Issue by minnhtutbagyi** [pipech/erpnext-docker-debian#39]
I am the newbie to docker and follow the step to set up production as per your manual. But stuck at the frappe container ID step. Please guide me the correct direction. Thanks in advance.

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> docker image ls
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
docker4w/nsenter-dockerd   latest              2f1c802f322f        4 months ago        187kB
PS C:\WINDOWS\system32> docker container ls
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
PS C:\WINDOWS\system32> docker pull pipech/erpnext-docker-debian:sta-py2-latest
sta-py2-latest: Pulling from pipech/erpnext-docker-debian
cd8eada9c7bb: Pull complete
d8b1a5347e4d: Pull complete
92788d81d6b5: Pull complete
52aff3ed3fa4: Pull complete
33ac4d5b22ed: Pull complete
1199d2f56ef7: Pull complete
8cdd05f54f03: Pull complete
d434a892d100: Pull complete
e86ed71dbea6: Pull complete
8481442f0ce1: Pull complete
c972c7b52725: Pull complete
7137e0aed0d2: Pull complete
Digest: sha256:49db0035d7589a34453deda3c7b2165d8624dffcfbd0edf8b08f23670cf5e19c
Status: Downloaded newer image for pipech/erpnext-docker-debian:sta-py2-latest
PS C:\WINDOWS\system32> docker image ls
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
pipech/erpnext-docker-debian   sta-py2-latest      69fef46a9930        4 weeks ago         2.97GB
docker4w/nsenter-dockerd       latest              2f1c802f322f        4 months ago        187kB
PS C:\WINDOWS\system32> docker container ls
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
PS C:\WINDOWS\system32> docker swarm init
Swarm initialized: current node (gw35at2m9ohw4v9jiqc1zkrcj) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join --token SWMTKN-1-4kao6xxxxxxxxxxxxxxxxxxxxx 192.168.65.3:2377

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.

PS C:\WINDOWS\system32> git clone https://github.com/pipech/erpnext-docker-debian.git
Cloning into 'erpnext-docker-debian'...
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 1323 (delta 26), reused 33 (delta 14), pack-reused 1260
Receiving objects: 100% (1323/1323), 198.23 KiB | 96.00 KiB/s, done.
Resolving deltas: 100% (737/737), done.
PS C:\WINDOWS\system32> cd erpnext-docker-debian/production_setup
PS C:\WINDOWS\system32\erpnext-docker-debian\production_setup> docker network create --driver overlay --scope swarm traefik_proxy
vrk3ik8tyu7inlv4atnjwiqbf
PS C:\WINDOWS\system32\erpnext-docker-debian\production_setup> docker stack deploy -c prd.yml prd1
Creating network prd1_default
Creating config prd1_redis-socketio-conf
Creating config prd1_traefik-conf
Creating config prd1_mariadb-conf
Creating config prd1_mariadb-init-conf
Creating config prd1_redis-cache-conf
Creating config prd1_redis-queue-conf
Creating service prd1_frappe
Creating service prd1_mariadb
Creating service prd1_redis-cache
Creating service prd1_redis-queue
Creating service prd1_redis-socketio
Creating service prd1_traefik
PS C:\WINDOWS\system32\erpnext-docker-debian\production_setup> docker ps -a
CONTAINER ID        IMAGE                                         COMMAND                  CREATED              STATUS              PORTS                                         NAMES
78d534a8ae7d        pipech/erpnext-docker-debian:sta-py2-latest   "/home/frappe/produc…"   1 second ago         Created                                                           prd1_frappe.1.ji0abe8pqj53fij8m7zxvjego
24474fb3ffad        pipech/erpnext-docker-debian:sta-py2-latest   "/home/frappe/produc…"   17 seconds ago       Created             3306-3307/tcp, 8000-8005/tcp, 9000-9005/tcp   prd1_frappe.1.bh5l9pdxyao6v3qtzciy19cw3
450a6e2ba149        pipech/erpnext-docker-debian:sta-py2-latest   "/home/frappe/produc…"   28 seconds ago       Created             3306-3307/tcp, 8000-8005/tcp, 9000-9005/tcp   prd1_frappe.1.0unwlq7ul6ha27gr58sq2fwa6
dd184940ab1e        pipech/erpnext-docker-debian:sta-py2-latest   "/home/frappe/produc…"   39 seconds ago       Created             3306-3307/tcp, 8000-8005/tcp, 9000-9005/tcp   prd1_frappe.1.0oklh9d1k3mbm4eewarkpgthd
b7356b7a5632        pipech/erpnext-docker-debian:sta-py2-latest   "/home/frappe/produc…"   50 seconds ago       Created             3306-3307/tcp, 8000-8005/tcp, 9000-9005/tcp   prd1_frappe.1.s9137a6sjoo73x4hgcxw55ygh
cda5b472e0a5        pipech/erpnext-docker-debian:sta-py2-latest   "/home/frappe/produc…"   About a minute ago   Created             3306-3307/tcp, 8000-8005/tcp, 9000-9005/tcp   prd1_frappe.1.xkuf9o598yyc9366sgjwhzp0d
PS C:\WINDOWS\system32\erpnext-docker-debian\production_setup> docker exec -it 78d534a8ae7d bash
Error: No such container: 78d534a8ae7d

**Comment by pipech** [comment]
It seems like docker is still downloading other image looking form there're only frappe image running. You should wait a while (like 5 mins) then run `docker ps -a` again.

**Comment by minnhtutbagyi** [comment]
Thanks.
I will try with `mas-py3-latest` in trial setup.
Best Regards
