### ISSUE TITLE
Trial Setup localhost not Up

### ISSUE THREAD

**Issue by minnhtutbagyi** [pipech/erpnext-docker-debian#40]
Reset the docker "Reset to factory defaults...' in docker setting and tried the easiest one (Trial Setup) with mas-py3-latest. But the http://localhost:8000/ show nothing. Don't know which one is wrong. 

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> docker pull pipech/erpnext-docker-debian:mas-py3-latest
mas-py3-latest: Pulling from pipech/erpnext-docker-debian
5e6ec7f28fb7: Pull complete
3cf17b373001: Pull complete
7b23a3f83a09: Pull complete
268608fc2c0a: Pull complete
163e85c235df: Pull complete
9bc1eeba2548: Pull complete
804806f68463: Pull complete
f729397d88e5: Pull complete
4c2ed157a37d: Pull complete
a8004303490a: Pull complete
b1a69f2f7cc9: Pull complete
b46b4b238e90: Pull complete
Digest: sha256:7a3eb9fd0e5ac009106600d7ba4b46162ff23671fd6c1576dcc7d2ff25053a0a
Status: Downloaded newer image for pipech/erpnext-docker-debian:mas-py3-latest
PS C:\WINDOWS\system32> docker run -d -p 8000-8005:8000-8005 -p 9000-9005:9000-9005 -p 3306-3307:3306-3307 pipech/erpnext-docker-debian:mas-py3-latest
d89469abb696e33331816cb71ea69b6dd080d0257c3242abc4ffc211e1a55e40
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: driver failed programming external connectivity on endpoint competent_bardeen (f5a9afbdec028a90375ce67c2a167de2252f2c2e46a04515cf1a14a537acb7bc): Error starting userland proxy: Bind for 0.0.0.0:3306 failed: port is already allocated.
PS C:\WINDOWS\system32> docker run -d -p 8000-8005:8000-8005 -p 9000-9005:9000-9005 pipech/erpnext-docker-debian:mas-py3-latest
32c1f97daeace55959e6f7fa8ade9792375f23a40236959b498c7218164bd641
PS C:\WINDOWS\system32> docker image ls
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
pipech/erpnext-docker-debian   mas-py3-latest      fd6f579bfaa2        17 hours ago        2.79GB
docker4w/nsenter-dockerd       latest              2f1c802f322f        4 months ago        187kB
PS C:\WINDOWS\system32> docker container ls
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
PS C:\WINDOWS\system32> docker ps -a
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS                     PORTS               NAMES
32c1f97daeac        pipech/erpnext-docker-debian:mas-py3-latest   "/usr/local/bin/entr…"   5 minutes ago       Exited (1) 4 minutes ago                       optimistic_hawking
d89469abb696        pipech/erpnext-docker-debian:mas-py3-latest   "/usr/local/bin/entr…"   5 minutes ago       Created                                        competent_bardeen

**Comment by minnhtutbagyi** [comment]
Container only running for a while and auto stop.

PS C:\WINDOWS\system32> docker run -d -p 8000-8005:8000-8005 -p 9000-9005:9000-9005 pipech/erpnext-docker-debian:mas-py3-latest
62cbedde3528090ddf85402fc9ecbd879a388b569169f9773b518aa41f06069a
PS C:\WINDOWS\system32> docker container ls
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS              PORTS                                                                               NAMES
62cbedde3528        pipech/erpnext-docker-debian:mas-py3-latest   "/usr/local/bin/entr…"   5 seconds ago       Up 3 seconds        0.0.0.0:8000-8005->8000-8005/tcp, 3306-3307/tcp, 0.0.0.0:9000-9005->9000-9005/tcp   awesome_grothendieck
PS C:\WINDOWS\system32> docker container ls
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS              PORTS                                                                               NAMES
62cbedde3528        pipech/erpnext-docker-debian:mas-py3-latest   "/usr/local/bin/entr…"   11 seconds ago      Up 8 seconds        0.0.0.0:8000-8005->8000-8005/tcp, 3306-3307/tcp, 0.0.0.0:9000-9005->9000-9005/tcp   awesome_grothendieck
PS C:\WINDOWS\system32> docker container ls
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS              PORTS                                                                               NAMES
62cbedde3528        pipech/erpnext-docker-debian:mas-py3-latest   "/usr/local/bin/entr…"   13 seconds ago      Up 10 seconds       0.0.0.0:8000-8005->8000-8005/tcp, 3306-3307/tcp, 0.0.0.0:9000-9005->9000-9005/tcp   awesome_grothendieck
PS C:\WINDOWS\system32> docker container ls
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS              PORTS                                                                               NAMES
62cbedde3528        pipech/erpnext-docker-debian:mas-py3-latest   "/usr/local/bin/entr…"   15 seconds ago      Up 12 seconds       0.0.0.0:8000-8005->8000-8005/tcp, 3306-3307/tcp, 0.0.0.0:9000-9005->9000-9005/tcp   awesome_grothendieck
PS C:\WINDOWS\system32> docker container ls
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS              PORTS                                                                               NAMES
62cbedde3528        pipech/erpnext-docker-debian:mas-py3-latest   "/usr/local/bin/entr…"   17 seconds ago      Up 14 seconds       0.0.0.0:8000-8005->8000-8005/tcp, 3306-3307/tcp, 0.0.0.0:9000-9005->9000-9005/tcp   awesome_grothendieck
PS C:\WINDOWS\system32> docker container ls
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS              PORTS                                                                               NAMES
62cbedde3528        pipech/erpnext-docker-debian:mas-py3-latest   "/usr/local/bin/entr…"   22 seconds ago      Up 20 seconds       0.0.0.0:8000-8005->8000-8005/tcp, 3306-3307/tcp, 0.0.0.0:9000-9005->9000-9005/tcp   awesome_grothendieck
PS C:\WINDOWS\system32> docker container ls
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS              PORTS                                                                               NAMES
62cbedde3528        pipech/erpnext-docker-debian:mas-py3-latest   "/usr/local/bin/entr…"   25 seconds ago      Up 22 seconds       0.0.0.0:8000-8005->8000-8005/tcp, 3306-3307/tcp, 0.0.0.0:9000-9005->9000-9005/tcp   awesome_grothendieck
PS C:\WINDOWS\system32> docker container ls
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS              PORTS                                                                               NAMES
62cbedde3528        pipech/erpnext-docker-debian:mas-py3-latest   "/usr/local/bin/entr…"   27 seconds ago      Up 24 seconds       0.0.0.0:8000-8005->8000-8005/tcp, 3306-3307/tcp, 0.0.0.0:9000-9005->9000-9005/tcp   awesome_grothendieck
PS C:\WINDOWS\system32> docker container ls
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS              PORTS                                                                               NAMES
62cbedde3528        pipech/erpnext-docker-debian:mas-py3-latest   "/usr/local/bin/entr…"   28 seconds ago      Up 26 seconds       0.0.0.0:8000-8005->8000-8005/tcp, 3306-3307/tcp, 0.0.0.0:9000-9005->9000-9005/tcp   awesome_grothendieck
PS C:\WINDOWS\system32> docker container ls
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS              PORTS                                                                               NAMES
62cbedde3528        pipech/erpnext-docker-debian:mas-py3-latest   "/usr/local/bin/entr…"   30 seconds ago      Up 27 seconds       0.0.0.0:8000-8005->8000-8005/tcp, 3306-3307/tcp, 0.0.0.0:9000-9005->9000-9005/tcp   awesome_grothendieck
PS C:\WINDOWS\system32> docker container ls
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS              PORTS                                                                               NAMES
62cbedde3528        pipech/erpnext-docker-debian:mas-py3-latest   "/usr/local/bin/entr…"   33 seconds ago      Up 30 seconds       0.0.0.0:8000-8005->8000-8005/tcp, 3306-3307/tcp, 0.0.0.0:9000-9005->9000-9005/tcp   awesome_grothendieck
PS C:\WINDOWS\system32> docker container ls
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
PS C:\WINDOWS\system32> docker container ls
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
PS C:\WINDOWS\system32> docker container ls
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
PS C:\WINDOWS\system32>

**Comment by minnhtutbagyi** [comment]
Docker logs showing mysqld is failed to start!

PS C:\WINDOWS\system32> docker logs gallant_colden
+ sudo service mysql start
Starting MariaDB database server: mysqld . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . failed!

**Comment by pipech** [comment]
Hi, I just tried this on my computer, it works. You should try restart your computer and try again.

**Comment by minnhtutbagyi** [comment]
Restart and tried, still failed. Will try on another laptop. Thanks a lot!

**Comment by stapeldev** [comment]
@minnhtutbagyi Run a netstat -a -d on your host, looks like possible port conflict...from your log above:

C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: driver failed programming external connectivity on endpoint competent_bardeen (f5a9afbdec028a90375ce67c2a167de2252f2c2e46a04515cf1a14a537acb7bc): Error starting userland proxy: Bind for 0.0.0.0:3306 failed: port is already allocated.

**Comment by minnhtutbagyi** [comment]
My another laptop is Windows 7 32bit and can't install docker toolbox to test. Read through others forum and they have similar MySQL issues at Mac OSX too. But mine is windows 10 host.
https://github.com/moby/moby/issues/34390

 @stapeldev yeah, in my host machine previously i have installed MySQL. After uninstalling MySQL from Win 10 host, port 3306 conflict issue is solved. 

Still have the issue of mysqld failed all @ :stable :mas-py2-latest :mas-py3-latest 
Host is window 10 Enterprise. Thanks.

**Comment by pipech** [comment]
Try this.

Run image with bash
`docker run -it -p 8000-8005:8000-8005 -p 9000-9005:9000-9005 -p 3306-3307:3306-3307 pipech/erpnext-docker-debian:mas-py3-latest bash`

Then manually start mysql
`sudo service mysql start`

Finally start bench
`bench start`

**Comment by minnhtutbagyi** [comment]
Tested with :mas-py3-latest image
First command execute successfully. 
Second command fail <sudo service mysql start>
Third command execute successfully. <bench start>
localhost:8000 is **UP** and can log in with Administrator : 12345
Can create a few items and showed items normally. Confused although command show mysqld failed but can create items (looks like sql is working normal). 
Will test with other image and report back.


`PS C:\WINDOWS\system32> docker run -it -p 8000-8005:8000-8005 -p 9000-9005:9000-9005 -p 3306-3307:3306-3307 pipech/erpnext-docker-debian:mas-py3-latest bash
frappe@062b166f591f:~/bench$ sudo service mysql start
[FAIL] Starting MariaDB database server: mysqld . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . failed!
frappe@062b166f591f:~/bench$ bench start
13:18:55 system           | redis_socketio.1 started (pid=475)
13:18:55 system           | schedule.1 started (pid=483)
13:18:56 redis_socketio.1 |                 _._
13:18:56 redis_socketio.1 |            _.-``__ ''-._
13:18:56 redis_socketio.1 |       _.-``    `.  `_.  ''-._           Redis 3.2.6 (00000000/0) 64 bit
13:18:56 redis_socketio.1 |   .-`` .-```.  ```\/    _.,_ ''-._
13:18:56 redis_socketio.1 |  (    '      ,       .-`  | `,    )     Running in standalone mode
13:18:56 redis_socketio.1 |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 12000
13:18:56 redis_socketio.1 |  |    `-._   `._    /     _.-'    |     PID: 494
13:18:56 redis_socketio.1 |   `-._    `-._  `-./  _.-'    _.-'
13:18:56 redis_socketio.1 |  |`-._`-._    `-.__.-'    _.-'_.-'|
13:18:56 redis_socketio.1 |  |    `-._`-._        _.-'_.-'    |           http://redis.io
13:18:56 redis_socketio.1 |   `-._    `-._`-.__.-'_.-'    _.-'
13:18:56 redis_socketio.1 |  |`-._`-._    `-.__.-'    _.-'_.-'|
13:18:56 redis_socketio.1 |  |    `-._`-._        _.-'_.-'    |
13:18:56 redis_socketio.1 |   `-._    `-._`-.__.-'_.-'    _.-'
13:18:56 redis_socketio.1 |       `-._    `-.__.-'    _.-'
13:18:56 redis_socketio.1 |           `-._        _.-'
13:18:56 redis_socketio.1 |               `-.__.-'
13:18:56 redis_socketio.1 |
13:18:56 redis_socketio.1 | 494:M 21 Feb 13:18:56.058 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
13:18:56 redis_socketio.1 | 494:M 21 Feb 13:18:56.058 # Server started, Redis version 3.2.6
13:18:56 redis_socketio.1 | 494:M 21 Feb 13:18:56.059 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
13:18:56 redis_socketio.1 | 494:M 21 Feb 13:18:56.059 * The server is now ready to accept connections on port 12000
13:18:56 system           | redis_cache.1 started (pid=486)
13:18:56 system           | worker_long.1 started (pid=491)
13:18:56 system           | redis_queue.1 started (pid=481)
13:18:56 redis_queue.1    |                 _._
13:18:56 redis_queue.1    |            _.-``__ ''-._
13:18:56 redis_queue.1    |       _.-``    `.  `_.  ''-._           Redis 3.2.6 (00000000/0) 64 bit
13:18:56 redis_queue.1    |   .-`` .-```.  ```\/    _.,_ ''-._
13:18:56 redis_queue.1    |  (    '      ,       .-`  | `,    )     Running in standalone mode
13:18:56 redis_queue.1    |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 11000
13:18:56 redis_queue.1    |  |    `-._   `._    /     _.-'    |     PID: 500
13:18:56 redis_queue.1    |   `-._    `-._  `-./  _.-'    _.-'
13:18:56 redis_queue.1    |  |`-._`-._    `-.__.-'    _.-'_.-'|
13:18:56 redis_queue.1    |  |    `-._`-._        _.-'_.-'    |           http://redis.io
13:18:56 redis_queue.1    |   `-._    `-._`-.__.-'_.-'    _.-'
13:18:56 redis_queue.1    |  |`-._`-._    `-.__.-'    _.-'_.-'|
13:18:56 redis_queue.1    |  |    `-._`-._        _.-'_.-'    |
13:18:56 redis_queue.1    |   `-._    `-._`-.__.-'_.-'    _.-'
13:18:56 redis_queue.1    |       `-._    `-.__.-'    _.-'
13:18:56 redis_queue.1    |           `-._        _.-'
13:18:56 redis_queue.1    |               `-.__.-'
13:18:56 redis_queue.1    |
13:18:56 redis_queue.1    | 500:M 21 Feb 13:18:56.134 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
13:18:56 redis_queue.1    | 500:M 21 Feb 13:18:56.136 # Server started, Redis version 3.2.6
13:18:56 redis_queue.1    | 500:M 21 Feb 13:18:56.136 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
13:18:56 redis_queue.1    | 500:M 21 Feb 13:18:56.136 * The server is now ready to accept connections on port 11000
13:18:56 redis_cache.1    |                 _._
13:18:56 redis_cache.1    |            _.-``__ ''-._
13:18:56 redis_cache.1    |       _.-``    `.  `_.  ''-._           Redis 3.2.6 (00000000/0) 64 bit
13:18:56 redis_cache.1    |   .-`` .-```.  ```\/    _.,_ ''-._
13:18:56 redis_cache.1    |  (    '      ,       .-`  | `,    )     Running in standalone mode
13:18:56 redis_cache.1    |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 13000
13:18:56 redis_cache.1    |  |    `-._   `._    /     _.-'    |     PID: 498
13:18:56 redis_cache.1    |   `-._    `-._  `-./  _.-'    _.-'
13:18:56 redis_cache.1    |  |`-._`-._    `-.__.-'    _.-'_.-'|
13:18:56 redis_cache.1    |  |    `-._`-._        _.-'_.-'    |           http://redis.io
13:18:56 redis_cache.1    |   `-._    `-._`-.__.-'_.-'    _.-'
13:18:56 redis_cache.1    |  |`-._`-._    `-.__.-'    _.-'_.-'|
13:18:56 redis_cache.1    |  |    `-._`-._        _.-'_.-'    |
13:18:56 redis_cache.1    |   `-._    `-._`-.__.-'_.-'    _.-'
13:18:56 redis_cache.1    |       `-._    `-.__.-'    _.-'
13:18:56 redis_cache.1    |           `-._        _.-'
13:18:56 redis_cache.1    |               `-.__.-'
13:18:56 redis_cache.1    |
13:18:56 redis_cache.1    | 498:M 21 Feb 13:18:56.146 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
13:18:56 redis_cache.1    | 498:M 21 Feb 13:18:56.146 # Server started, Redis version 3.2.6
13:18:56 redis_cache.1    | 498:M 21 Feb 13:18:56.146 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
13:18:56 redis_cache.1    | 498:M 21 Feb 13:18:56.146 * The server is now ready to accept connections on port 13000
13:18:56 system           | web.1 started (pid=485)
13:18:56 system           | socketio.1 started (pid=487)
13:18:56 system           | watch.1 started (pid=490)
13:18:56 system           | worker_default.1 started (pid=484)
13:18:56 system           | worker_short.1 started (pid=489)
13:18:59 socketio.1       | listening on *: 9000
13:19:02 web.1            |  * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
13:19:02 web.1            |  * Restarting with inotify reloader
13:19:02 watch.1          | yarn run v1.13.0
13:19:03 watch.1          | $ node rollup/watch.js
13:19:03 web.1            |  * Debugger is active!
13:19:03 web.1            |  * Debugger PIN: 339-958-428
13:19:08 watch.1          |
13:19:08 watch.1          | Rollup Watcher Started
13:19:08 watch.1          |
13:19:08 watch.1          | Watching...
13:19:09 watch.1          | Rebuilding frappe-web.css
13:19:09 watch.1          | Rebuilding chat.js
13:19:11 watch.1          | Rebuilding frappe-web.min.js
13:19:12 watch.1          | Rebuilding control.min.js
13:19:14 watch.1          | Rebuilding dialog.min.js
13:19:15 watch.1          | Rebuilding desk.min.css
13:19:15 watch.1          | Rebuilding frappe-rtl.css
13:19:15 watch.1          | Rebuilding desk.min.js
13:19:17 watch.1          | Rebuilding module.min.css
13:19:17 watch.1          | Rebuilding form.min.css
13:19:17 watch.1          | Rebuilding form.min.js
13:19:17 watch.1          | (node:596) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
13:19:18 watch.1          | Rebuilding list.min.css
13:19:18 watch.1          | Rebuilding list.min.js
13:19:18 watch.1          | Rebuilding report.min.css
13:19:18 watch.1          | Rebuilding report.min.js
13:19:19 watch.1          | Rebuilding web_form.min.js
13:19:20 watch.1          | Rebuilding web_form.css
13:19:20 watch.1          | Rebuilding print_format_v3.min.js
13:19:20 watch.1          | Rebuilding email.css
13:19:20 watch.1          | Rebuilding erpnext.css
13:19:20 watch.1          | Rebuilding marketplace.css
13:19:20 watch.1          | Rebuilding erpnext-web.min.js
13:19:20 watch.1          | Rebuilding erpnext-web.css
13:19:20 watch.1          | Rebuilding marketplace.min.js
13:19:23 watch.1          | Rebuilding erpnext.min.js
13:19:23 watch.1          | Rebuilding item-dashboard.min.js
13:43:32 web.1            | 172.17.0.1 - - [21/Feb/2019 13:43:32] "GET / HTTP/1.1" 200 -`

**Comment by pipech** [comment]
Hi, could you check mysql status by `sudo service mysql status` inside container.

And check docker version by `docker info` on host.

**Comment by minnhtutbagyi** [comment]
Docker Info

PS C:\WINDOWS\system32> docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 7
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.837GiB
Name: linuxkit-00155d006410
ID: VKC3:IESM:L5YT:FCUR:M6LA:XWVH:USE2:A3RB:Y3RD:4TEI:RVAO:6ZNK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 35
 Goroutines: 70
 System Time: 2019-02-21T16:31:53.6402389Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

PS C:\WINDOWS\system32>

**Comment by minnhtutbagyi** [comment]
mysql status

frappe@f63d3db64469:~/bench$ sudo service mysql status
[info] /usr/bin/mysqladmin  Ver 9.1 Distrib 10.3.12-MariaDB, for debian-linux-gnu on x86_64
Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Server version          10.3.12-MariaDB-1:10.3.12+maria~stretch
Protocol version        10
Connection              Localhost via UNIX socket
UNIX socket             /var/run/mysqld/mysqld.sock
Uptime:                 9 min 11 sec

Threads: 8  Questions: 182  Slow queries: 0  Opens: 36  Flush tables: 1  Open tables: 28  Queries per second avg: 0.330.
frappe@f63d3db64469:~/bench$

**Comment by pipech** [comment]
Normally mysql shouldn't start by it self.

Could you run another container
`docker run -it -p 8000-8005:8000-8005 -p 9000-9005:9000-9005 -p 3306-3307:3306-3307 pipech/erpnext-docker-debian:mas-py3-latest bash`

Then check mysql status
`sudo service mysql status`

If it's not running run
`sudo service mysql start`

**Comment by minnhtutbagyi** [comment]
Before Bench Start
[(https://ibb.co/8Xgzj4r)]

After Bench Start
[(https://ibb.co/w7xF1LJ)]

**Comment by pipech** [comment]
To be sure that we using same image could you tried with image tags `11.1.4-py3`

If it not works, I've no idea how it happen and how to fix it. 
MySQL shouldn't failed to start and MySQL also shouldn't start by it self out of no where.

My last suggestion is tried to update docker version but I'm not sure if this will works.

**Comment by minnhtutbagyi** [comment]
I have two drives C and D (128gb SSD and 1 tb HDD)

Setting > Advanced > Disk image location > Default C drive
https://ibb.co/FsHTpmN

Setting > Advanced > Disk image location > D drive
https://ibb.co/5k5P81Z

Thank you indeed @pipech ! ขอขอบคุณคุณแน่นอน!
Best Regards

**Comment by pipech** [comment]
It's my pleasure.

Hey it works!, did you figure out what is the problems?

**Comment by minnhtutbagyi** [comment]
I have previously changed disk drive location to D drive because low space at C. That is issue.
If leave default disk drive location at C drive, working like a charm. 

May be SSD and HDD read/write speed to command mysqld to start loading. 
Or docker require MobyLinuxVM.vhdx (specifically ERPNext image) to sit the same partition as Windows.
Due to complexity of ERPNext image it need to sit inside C drive or faster i/o drive.
But some light image (standalone mariadb image) working well under D drive configuration. 
That is myself conclusion. Thanks

Best Regards
