### ISSUE TITLE
development_setup - why so many ports?

### ISSUE THREAD

**Issue by vrms** [pipech/erpnext-docker-debian#41]
just for my understanding:

>     ports:
>      - "8000-8005:8000-8005" #webserver_port
>      - "9000-9005:9000-9005" #socketio_port
why do you provide so many ports (6 for the webserver, 6 for socketio) and not just 1 (`8000:8000`, `9000:9000`)?

On my first 2 instances (`v11.1.9-py3`, `10.1.81-py2`) only the 8000 port serves the ERPNExt website anyway

**Comment by pipech** [comment]
Yes, normally ERPNext will be serves using port 8000 but sometimes it moves to port 8001 or 8002 (Happens to me once of twice).

So 8000-8005:8000-8005 is just in case ERPNext decided to serve on port 8001 or 8002 and socketio is the same things.

**Comment by vrms** [comment]
ok, got it. Thanks for clarifying.
