### ISSUE TITLE
how to contribute to the documentation?

### ISSUE THREAD

**Issue by vrms** [pipech/erpnext-docker-debian#42]
how could anyone send a PR for contributions to the documentation (https://pipech.github.io/erpnext-docker-debian/)?

**Comment by pipech** [comment]
Hi, @vrms 
Thank you for taking interest in this project.

https://pipech.github.io/erpnext-docker-debian is generate by [GitHub Pages](https://pages.github.com) using [Jekyll](https://jekyllrb.com/docs) and written in [Markdown Language](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet).

Source code are in [erpnext-docker-debian/docs](https://github.com/pipech/erpnext-docker-debian/tree/master/docs)

If you have any questions, please let me know.

**Comment by vrms** [comment]
thx

**Comment by dawoodjee** [comment]
Great work. Would have been nice if you used a simpler template so that we can easily contribute to the documentation right within from Github.

**Comment by pipech** [comment]
Yes, I started to think we should do that.
How about we start using Github Wiki ?

Could you guys write up a new tutorial using Github Wikil ?
As you can see English is not my first language.

If some of the old tutorial doesn't clear please let me know.
I'll be please to clarify.

**Comment by dawoodjee** [comment]
You've made the right decision. I'll pitch in whenever I can. Go ahead and create the documentation you can and we'll also help with the grammar and typo corrections.

**Comment by dawoodjee** [comment]
I've copied all the documentation to the Github wiki as far as I can tell. Made a few grammatical corrections, we can rely on the community to spot and improve this some more. Also altered the formatting slightly to reduce on the bullets.

**Comment by pipech** [comment]
Sorry for late reply, it's been a long holiday in Thailand.

Thank you very much for [Wiki](https://github.com/pipech/erpnext-docker-debian/wiki) and #50
