### ISSUE TITLE
Slideshow Creation Fails w/ error: AttributeError: 'map' object has no attribute 'split'

### ISSUE THREAD

**Issue by stapeldev** [pipech/erpnext-docker-debian#43]
So I've searched around a bit and I see that back when v11 was in dev there was a similar issue: https://discuss.erpnext.com/t/website-slide-show-attributeerror-map-object-has-no-attribute-split/43904 ,however, I've tested this with the "Production" vm image that is provided by ERPNext and cannot reproduce the error. Wondering if @pipech is experiencing the same with the latest docker image?  It's clearly a python error and I think it's a bit misleading, but I could use some guidance on this. Here's a snippet of the specific error I am getting:

	Traceback (most recent call last):
	  File "/home/frappe/bench/apps/frappe/frappe/app.py", line 61, in application
		response = frappe.handler.handle()
	  File "/home/frappe/bench/apps/frappe/frappe/handler.py", line 21, in handle
		data = execute_cmd(cmd)
	  File "/home/frappe/bench/apps/frappe/frappe/handler.py", line 56, in execute_cmd
		return frappe.call(method, **frappe.form_dict)
	  File "/home/frappe/bench/apps/frappe/frappe/__init__.py", line 1019, in call
		return fn(*args, **newargs)
	  File "/home/frappe/bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
		doc.save()
	  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 260, in save
		return self._save(*args, **kwargs)
	  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 283, in _save
		self.insert()
	  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 222, in insert
		self.run_before_save_methods()
	  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 876, in run_before_save_methods
		self.run_method("validate")
	  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 772, in run_method
		out = Document.hook(fn)(self, *args, **kwargs)
	  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 1048, in composer
		return composed(self, method, *args, **kwargs)
	  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 1031, in runner
		add_to_return_value(self, fn(self, *args, **kwargs))
	  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 766, in <lambda>
		fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
	  File "/home/frappe/bench/apps/frappe/frappe/website/doctype/website_slideshow/website_slideshow.py", line 14, in validate
		self.validate_images()
	  File "/home/frappe/bench/apps/frappe/frappe/website/doctype/website_slideshow/website_slideshow.py", line 25, in validate_images
		result = frappe.get_all("File", filters={ "file_url":("in", files) }, fields="is_private")
	  File "/home/frappe/bench/apps/frappe/frappe/__init__.py", line 1274, in get_all
		return get_list(doctype, *args, **kwargs)
	  File "/home/frappe/bench/apps/frappe/frappe/__init__.py", line 1247, in get_list
		return frappe.model.db_query.DatabaseQuery(doctype).execute(None, *args, **kwargs)
	  File "/home/frappe/bench/apps/frappe/frappe/model/db_query.py", line 93, in execute
		result = self.build_and_run()
	  File "/home/frappe/bench/apps/frappe/frappe/model/db_query.py", line 105, in build_and_run
		args = self.prepare_args()
	  File "/home/frappe/bench/apps/frappe/frappe/model/db_query.py", line 124, in prepare_args
		self.build_conditions()
	  File "/home/frappe/bench/apps/frappe/frappe/model/db_query.py", line 303, in build_conditions
		self.build_filter_conditions(self.filters, self.conditions)
	  File "/home/frappe/bench/apps/frappe/frappe/model/db_query.py", line 324, in build_filter_conditions
		conditions.append(self.prepare_filter_condition(f))
	  File "/home/frappe/bench/apps/frappe/frappe/model/db_query.py", line 382, in prepare_filter_condition
		values = values.split(",")
	AttributeError: 'map' object has no attribute 'split'

**Comment by pipech** [comment]
Hi, to narrow the problem down could you check ERPNext VM image version and tried to reproduce error on trail setup using same or closest version to ERPNext VM image.

**Comment by stapeldev** [comment]
Sorry for the delay @pipech. I think it is definitely related to Python V 3. I now have four environments running. 

Environment 1
---
    ERPNext Production VM using VirtualBox:
    ERPnext: 11.1.11
    Frappe: 11.1.11
    Python Version 2.7.12
    Slideshow Creation: Works
---
Environment 2 (My Production Docker Instance)
---
    ERPNext Production Docker Image based on  pipech/erpnext-docker-debian:11.1.4-py3
    Bench Update to latest version:
    frappe@283b5e8e6bd1:/bench$ python --version
    Python 2.7.13
    frappe@283b5e8e6bd1:/bench$ python3 --version
    Python 3.5.3
    frappe@283b5e8e6bd1:/bench$ bench version
    erpnext 11.1.11
    frappe 11.1.11
    frappe@283b5e8e6bd1:/bench$ exit
    283b5e8e6bd1        pipech/erpnext-docker-debian:11.1.4-py3   "/home/frappe/produc…"   10 days ago         Up 10 days          3306-3307/tcp, 8000-8005/tcp, 9000-9005/tcp
    Slideshow: Not Working

>Note: I did a bench restart while exec'd into the container, however, when I go to the web interface and go to the help about section, it's still showing that the web interface is running 11.1.4 (even though while I was updating in the container, the web interface acknowledged that it was running a new version with a pop up telling me I needed to refresh my session.
---
Environment 3
---
    pipech/erpnext-docker-debian:11.1.9-py3 (Trial Configuration)
    frappe@005fdf7ff457:/bench$ bench version
    erpnext 11.1.9
    frappe 11.1.8
    frappe@005fdf7ff457:/bench$ python --version
    Python 2.7.13
    frappe@005fdf7ff457:/bench$ python3 --version
    Python 3.5.3
    Slideshow: Not Working

---
Environment 4
---
    pipech/erpnext-docker-debian:11.1.9-py2 (Trial Configuration)
    frappe@419b99810927:/bench$ bench version
    erpnext 11.1.9
    frappe 11.1.8
    frappe@419b99810927:/bench$ python --version
    Python 2.7.13
    frappe@419b99810927:/bench$ python3 --version
    Python 3.5.3
    Slideshow: Working

---
Recap
---
*ERPNext VM Running last Frappe/ERPnext using Python 2.7 - Works
*ERPNext Docker Image Running 11.1.9/11.1.8 using Python 2.7 - Works
*ERPNext Docker Image Running 11.1.9/11.1.8 using Python 3.5 - Fails
*ERPNext Docker Image Running 11.1.11/11.1.11 using Python 3.5 - Fails

I am still learning where to look to verify python configuration, but that's the latest from my test.

**Comment by pipech** [comment]
Wow, thank you for such detail testing.

Since the problem is with ERPNext code, the fix should be done there.
https://github.com/frappe/erpnext/issues/14416

I've tried to find the underlying problem but I can't find anything obvious that might cause this problem.

Sorry I can't help much.

**Comment by stapeldev** [comment]
@pipech I think you're right. Sorry to bother you on this one. Good to know that the slideshow (and probably other things) isn't quite functional in ERPNext on PY3. I am learning slowly. If I find something I will report back here, just in case it helps others. Thanks again and hope this didn't side track you too much.

**Comment by stapeldev** [comment]
@pipech Ok, just a follow up on this, I've discovered something about this error. It essentially means that python is expecting a list string, but it's not getting a list string, it's getting a map object.  I found the following "fix" that upon checking my test instance that is not working, the fix is not in place.

https://github.com/frappe/frappe/commit/e6d5a61186def4f8e8c4898c81e275d85b20b45b

When I apply the fix to my test environment, the error goes away and I can now create slideshows. 

Unfortunately, I am now running into an issue with image uploads resetting, but that might be a different problem.  Just thought I would pass this along since it seems to be specific to a version of code included in your docker images.

**Comment by pipech** [comment]
If it works in test env but not in production env, you could tried `bench restart` and see if it works (Normally it should)

**Comment by stapeldev** [comment]
Ok, just a follow up on this. I think the upload issue was related to some other problems I was experiencing. I am now running the latest version of your 11.1.11-py3 image, I had to change the code again in the website_slideshow.py per the above fix, but I can now create slideshows and upload images successfully.  @pipech

**Comment by pipech** [comment]
The best way is to create pull request to frappe/frappe, https://github.com/frappe/frappe/pull/6103 this one has been merge into version 12. You should create pull request for version 11.

But until that has been fixed you either manually edit that line or create new image on top of 
11.1.11-py3 and use `sed` to change that line.

Some thing like this

	FROM pipech/erpnext-docker-debian:11.1.4-py3
	RUN sed [sed command to change that line]

**Comment by stapeldev** [comment]
Thanks for the insight @pipech I really appreciate your time. You can close this issue.
