### ISSUE TITLE
Production Setup with Private IP

### ISSUE THREAD

**Issue by minnhtutbagyi** [pipech/erpnext-docker-debian#44]
Have tried and passed production setup in my docker pipech/erpnext-docker-debian:12.x.x-190226-py3. But can't browse through local machine, because am testing inside my local machine. 

Do noted "**This setup is meant to run on server with public IP address and domain pointing to those IP address, otherwise it won’t work**."

How could I setup the production setting with localhost browsing same as Trial setup?

Thanks in advance!

**Comment by pipech** [comment]
Can you set Hostname on local machine or it must be an IP address?

If you can use Hostname, disable HTTPS on traefik should be enough.
You can disable HTTPS by change `erpnext-docker-debian/production_setup/conf/traefik-conf/traefik.toml` to

	logLevel = "DEBUG"

	defaultEntryPoints = ["https","http"]

	[docker]
	endpoint = "unix:///var/run/docker.sock"
	exposedByDefault = false

	[metrics]
		[metrics.prometheus]

	[entryPoints]
		[entryPoints.http]
		address = ":80"

**Comment by minnhtutbagyi** [comment]
Thanks, Sir! I will try it out and report back on tomorrow.

**Comment by minnhtutbagyi** [comment]
Thanks, Sir! I will try it out and report back on tomorrow.

**Comment by minnhtutbagyi** [comment]
WoW! Working well. Follow instructions and map hostname (127.0.0.1 xyz.com) to C:\Windows\System32\drivers\etc\hosts.
If possible, would like to know how to setup by private IP address too.
Thanks with Regards!

**Comment by pipech** [comment]
You have to 
1. disable multi-tenancy setting on frappe container
2. config traefik to redirect ip-address to frappe container (or remove traefik and add port 80 to frappe container and directly access frappe container)

**Comment by minnhtutbagyi** [comment]
will try. Thanks
