### ISSUE TITLE
Production Setup: DB access denied

### ISSUE THREAD

**Issue by DeMuu** [pipech/erpnext-docker-debian#47]
Hi,

I followed the production setup guide and when executing `. init.sh` in the frappe container I get a python error with the last line being

`pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'10.0.1.16' (using password: YES)")`

and I'm immediately kicked out of the container.

I hope it's not a mere noob issue. Tried to but couldn't find anything related in the closed issues.

Appreciate your help!

**Comment by DeMuu** [comment]
ℹ️  Maybe I should mention that the domain I'm using is a subdomain

**Comment by pipech** [comment]
Hi,

Did you change mariaDB password both of these files [common_site_config_docker.json](https://github.com/pipech/erpnext-docker-debian/blob/908d3aae5d8b910d1242e03ffc7e27876d799d94/production_setup/conf/frappe-docker-conf/common_site_config_docker.json#L14) and [db.yml](https://github.com/pipech/erpnext-docker-debian/blob/908d3aae5d8b910d1242e03ffc7e27876d799d94/production_setup/db.yml#L10) ? These 2 password should match.

**Comment by DeMuu** [comment]
Hi,

no I intended to at first but then did a `git reset` to make sure this was not the issue. Might have not cleared everything perfectly cause I tried again from scratch and it worked.
Thanks and sorry for taking your time!
