### ISSUE TITLE
External mariadb and configs

### ISSUE THREAD

**Issue by mannp** [pipech/erpnext-docker-debian#51]
Hi there

Thanks for the builds.

I wondered do you have a production build with the ability to have an external mariadb database and if so which configs do I update to redirect to my external db docker?

Thanks in advance.

**Comment by mannp** [comment]
I see production needs docker compose which I don't have on unraid, so perhaps not what I am looking for.

I am obviously running in trial mode..

**Comment by pipech** [comment]
Hi, production setup use `docker stack` not `docker-compose`.

**Comment by mannp** [comment]
Hi, Unraid doesn't have it, so I have to create a docker file for each docker and manually link them together, unfortunately.
