### ISSUE TITLE
Domain Production Configuration

### ISSUE THREAD

**Issue by sebasalvarado** [pipech/erpnext-docker-debian#53]
Thanks for this repo! Is really helpful :)

I just have a quick question, in your `Production Setup` Wiki one of the steps is to edit `In production_setup/prd.yml`

However, that file does not exist, is it a typo or should I create the file and only write:
```
labels:
    - "traefik.frontend.rule=Host:example1.com"
```

**Comment by sebasalvarado** [comment]
Also, where am I supposed to select the frappe image

```
Change Frappe image tag to current version

You should change pipech/erpnext-docker-debian:mas-py3-latest image to specific version number you prefer ie. pipech/erpnext-docker-debian:11.1.3-py3
```
Thanks again!

**Comment by pipech** [comment]
> I just have a quick question, in your `Production Setup` Wiki one of the steps is to edit `In production_setup/prd.yml`


Sorry, I've separated prd.yml into multiple yml file and forgot to update wiki. It should be in `production_setup/frappe.yml`

---

> Also, where am I supposed to select the frappe image
> 


You should change it in frappe.yml.
```
services:
    frappe:
        image: pipech/erpnext-docker-debian:mas-py3-latest
```
---

Cheers!

**Comment by sebasalvarado** [comment]
Thanks @pipech! That makes sense.

I have another question, I followed the whole Production Setup tutorial and I'm getting a 404 when trying to reach the server from the browser.

This is what I see on `docker ps`

<img width="1302" alt="Screen Shot 2019-05-27 at 12 34 31 PM" src="https://user-images.githubusercontent.com/15041987/58431453-d7b7f200-807b-11e9-8c49-2de6a2fa0f81.png">

You can see the 404 if you go to this URL: https://produccion.epsilontech.io/

After checking the logs, this is what I see is the problem:

```
time="2019-05-27T03:16:16Z" level=error msg="Unable to obtain ACME certificate for domains \"example1.com\" detected thanks to rule \"Host:example1.com\" : unable to generate a certificate for the domains [example1.com]: acme: Error -> One or more domains had a problem:\n[example1.com] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: Invalid response from http://www.example1.com/.well-known/acme-challenge/8y3M56uJupIhZo12aDcr25Suc_iVV1tzEd65Kc5PA2Y [69.94.6.39]: \"<!DOCTYPE HTML PUBLIC \\\"-//IETF//DTD HTML 2.0//EN\\\">\\n<html><head>\\n<title>404 Not Found</title>\\n</head><body>\\n<h1>Not Found</h1>\\n<p\", url: \n"

```

I have not changed an `example1.com` somewhere in some file, but I can't find where that is. I have gone through the Wiki many times and it doesn't fix it. Would appreciate your help!

This is what I have on `production_setup/conf/traefik-conf/traefik.toml`

```
[acme]
email = "sebastian@epsilontech.io"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onHostRule = true
    [acme.httpChallenge]
    entryPoint = "http"

```

**Comment by pipech** [comment]
> I have not changed an `example1.com` somewhere in some file, but I can't find where that is. I have gone through the Wiki many times and it doesn't fix it. Would appreciate your help!

It's in production_setup/frappe.yml
https://github.com/pipech/erpnext-docker-debian/blob/eaefb2bd43ced6a635ff2a735674aa3eb00639fb/production_setup/frappe.yml#L16-L21

---

Something wrong with your config, frappe container is not running.
Did you change this to your domain?

https://github.com/pipech/erpnext-docker-debian/blob/eaefb2bd43ced6a635ff2a735674aa3eb00639fb/production_setup/env/frappe_app.env#L7-L13


---

After changing those config you should take down the whole stack and run it again.
If everything working fine there should be 6 container running (3redis, 1traefik, 1mariadb, 1frappe).

If frappe container is not running you should try `docker ps -a` then `docker logs <container id>` and see what is the error.

**Comment by valentincauro** [comment]
Exactly the same issue… I followed precisly the guide, 2 times…
Question : Is that possible to lunch all without ssl like the following :
`logLevel = "DEBUG"

defaultEntryPoints = ["https","http"]
#defaultEntryPoints = ["http"]

[docker]
endpoint = "unix:///var/run/docker.sock"
exposedByDefault = false

[metrics]
    [metrics.prometheus]

[entryPoints]
    [entryPoints.http]
    address = ":80"
#        [entryPoints.http.redirect]
#        entryPoint = "https"
#    [entryPoints.https]
#    address = ":443"
#        [entryPoints.https.tls]

#[acme]
#email = "mail@me.com"
#storage = "/etc/traefik/acme/acme.json"
#entryPoint = "https"
#onHostRule = true
#    [acme.httpChallenge]
#    entryPoint = "http"
`

Thanks
