### ISSUE TITLE
Error in VSCode container

### ISSUE THREAD

**Issue by amrit-citrusleaf** [pipech/erpnext-docker-debian#59]
First of all, thanks for creating this repo. It's a lifesaver for frappe developers.

I'm getting the following error when opening the folder in VSCode insider build (https://github.com/pipech/erpnext-docker-debian/wiki/Development-setup-Inside-Container-with-VS-Code) - 

ERROR: for development_setup_vscode_devcontainer_frappe_1  Cannot start service frappe: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/home/frappe/bench/entrypoint.sh\": permission denied": unknown

I followed the steps outlined in the Wiki page. Let me know if I'm missing something. Thanks.

**Comment by pipech** [comment]
Hi,

Did you build image by your self or pulling from docker hub?

If you pull from docker hub, which image tag did you use?

If you use `mas-py3-latest` tag, could you try using `11-1-14_py3` tag?

Can you run image from docker cmd ?
`docker run -d -p 8000-8005:8000-8005 -p 9000-9005:9000-9005 -p 3306-3307:3306-3307 pipech/erpnext-docker-debian:mas-py3-latest`

**Comment by amrit-citrusleaf** [comment]
Yes, the trial setup works absolutely fine with pipech/erpnext-docker-debian:mas-py3-latest. Getting MySQL password error with development setup as well. I'll try with tag 11-1-14_py3 and update. Thanks!

**Comment by amrit-citrusleaf** [comment]
I pulled the image from docker hub.

**Comment by pipech** [comment]
Close due to inactivity.
