### ISSUE TITLE
Production setup

### ISSUE THREAD

**Issue by clefavelli** [pipech/erpnext-docker-debian#60]
During the installation of production setup I met the following challenges:
I am installing to a digital ocean server with an IP address no domain name established yet and am wondering. What should I place here : 

 - benchNewSiteName=example1.com
  - NGINX_SERVER_NAME=example1.com

and also here :+1: 

docker stack deploy -c proxy.yml <proxy_stack_name> docker stack deploy -c db.yml <db_stack_name> docker stack deploy -c frappe.yml <frappe_stack_name>

Whats is to be replaced in between the angle brackets, where do I get those variables.

**Comment by pipech** [comment]
Check this out if you want to use Production Setup with Private IP https://github.com/pipech/erpnext-docker-debian/issues/44

> docker stack deploy -c proxy.yml <proxy_stack_name> docker stack deploy -c db.yml <db_stack_name> docker stack deploy -c frappe.yml <frappe_stack_name>

You will be the one who set those names, you can name it to be anythings.

**Comment by pipech** [comment]
Close due to inactivity, feel free to re-open.

Cheers
