### ISSUE TITLE
Dockerhub image doesnt launch on Rancher 2.x

### ISSUE THREAD

**Issue by ViableClanMember** [pipech/erpnext-docker-debian#61]
```
+ sudo service mysql start
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
```

affects all versions i have tried (multiple), including 11.1.47-py3

**Comment by ViableClanMember** [comment]
More info at https://github.com/rancher/rancher/issues/13549

**Comment by pipech** [comment]
Sorry for late reply, I've been really busy this week.

I can't help you with that, I've never used Rancher.

Sorry
