### ISSUE TITLE
Update production setup to v12

### ISSUE THREAD

**Issue by Rashidsalim** [pipech/erpnext-docker-debian#62]
I have a successful deployment of production setup. How can I upgrade to V12 of ERPNEXT?
Thank you

**Comment by pipech** [comment]
I've just update and add new image version 12.

The image tags are `pipech/erpnext-docker:12.0.2-py3` and `pipech/erpnext-docker:v12-py3-latest`

Cheers!

**Comment by Rashidsalim** [comment]
Thanks!
I have changed the image tag in the frappe.yml file to `12.0.2-py3` but after redeploying the stack using
`docker stack deploy -c frappe.yml erpnext_frappe_stack` I'm getting an internal server error in the homepage.
![image](https://user-images.githubusercontent.com/37694861/61996222-afa83780-b09a-11e9-8b3c-1096007d12aa.png)

**Comment by pipech** [comment]
It seems like you have both v11 and v12 running at the same time, you should remove v11 stack first.

**Comment by ddsultan** [comment]
@Rashidsalim, Were you able to resolve the issue? I am having the same one.
