### ISSUE TITLE
VS code remote Development set fails

### ISSUE THREAD

**Issue by ruhusobeje** [pipech/erpnext-docker-debian#63]
For some reason, development setup in VS code remote fails with following :
![image](https://user-images.githubusercontent.com/36888881/63066765-b546af80-bed9-11e9-9d56-2415d1dc03f5.png)

`Step 8/8 : ENV DEV_SERVER=1
 ---> Running in 63a8a4d13fe7
Removing intermediate container 63a8a4d13fe7
 ---> 0ab4aab426da
Successfully built 0ab4aab426da
Successfully tagged devcontainer_frappe:latest
WARNING: Image for service frappe was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating devcontainer_frappe_1 ... done
Attaching to devcontainer_frappe_1
frappe_1  | standard_init_linux.go:211: exec user process caused "no such file or directory"
devcontainer_frappe_1 exited with code 1`

I am using this image:
docker pull pipech/erpnext-docker-debian:mas-py3-latest

I verified that entrypoint.sh has EOL as LF.

**Comment by pipech** [comment]
Hi,

Sorry I've been really busy these past 2 weeks.

I've just tried with

    Image: `pipech/erpnext-docker-debian:12.0.8-py3`
    OS: Windows 10
    VsCode: 1.38.0-insider

It works as it should. Could you try again using `pipech/erpnext-docker-debian:12.0.8-py3` image?

**Comment by pipech** [comment]
Close due to in-activities, please feel free to re-open if needed.
