### ISSUE TITLE
How to use `bench-start` & `bench-py-debug`?

### ISSUE THREAD

**Issue by chesterwu** [pipech/erpnext-docker-debian#64]
I followed the dev setup in this guide
https://github.com/pipech/erpnext-docker-debian/wiki/Development-setup-Inside-Container-with-VS-Code

but I can't use the debug tools
```
$ bench-start
sh: 6: bench-start: not found
$ bench-py-debug
sh: 5: bench-py-debug: not found
```
What should I do if I want to debug?

**Comment by pipech** [comment]
Hi,

The command is `bench start` with no "-"
