### ISSUE TITLE
Issue with setup wizard - step5

### ISSUE THREAD

**Issue by sindile** [pipech/erpnext-docker-debian#69]
I am using this image - pipech/erpnext-docker-debian:12.x.x-191015-py3
I am unable to proceed beyond step5. Any idea what could be wrong. I had chosen country to be South Africa. Thanks
![image](https://user-images.githubusercontent.com/1027916/67930371-4cadcb80-fbc8-11e9-9dc1-3a2069af5542.png)

**Comment by sindile** [comment]
This seems to be related to chart of accounts for South Africa.
When I change the country to USA I am able to complete all the steps in the setup wizard.

**Comment by pipech** [comment]
It's definitely ERPNext bug, you should open issues on [ERPNext github](https://github.com/frappe/erpnext).

Cheers!
