### ISSUE TITLE
Setup Node Exporter on AWS EC2 go version issue

### ISSUE THREAD

**Issue by ahmadRagheb** [pipech/erpnext-docker-debian#70]
node_exporter]$ make
Makefile.common:54: This repository requires Go >= 1.11 because of Go modules
Makefile.common:55: Some recipes may not work as expected as the current Go runtime is 'go1.10.3'
>> checking code style
>> checking license header
>> running golangci-lint
/home/ec2-user/go/bin/golangci-lint run ./...
ERRO Running error: context loading failed: failed to load program with go/packages: unsupported version of go: exit status 2: flag provided but not defined: -compiled
usage: list [-e] [-f format] [-json] [build flags] [packages]
Run 'go help list' for details.
 
make: *** [common-lint] Error 3

**Comment by ahmadRagheb** [comment]
Go >= 1.11   i try it with .1.13.3

**Comment by pipech** [comment]
Close due to inactivity, feel free to re-open if needed.
