### ISSUE TITLE
question on proxy_stack_name

### ISSUE THREAD

**Issue by ahmadRagheb** [pipech/erpnext-docker-debian#71]
docker stack deploy -c proxy.yml <proxy_stack_name>

docker stack deploy -c db.yml <db_stack_name>

docker stack deploy -c frappe.yml <frappe_stack_name>

what does  proxy_stack_name db_stack_name frappe_stack_name  mean ?

**Comment by ahmadRagheb** [comment]
also Deploy stack using prd.yml as prd1 stack (In production folder where prd.yml is)

i didn't found a prd.yml

**Comment by pipech** [comment]
> what does proxy_stack_name db_stack_name frappe_stack_name mean ?

You can name it as you want.

> also Deploy stack using prd.yml as prd1 stack (In production folder where prd.yml is)

Sorry, prd.yml is old format. I seperated prd.yml into frappe.yml, proxy.yml and db.yml, and I forgot to update the wiki.

I've updated the wiki, please let me know if you have any questions.

**Comment by pipech** [comment]
Close due to inactivity, feel free to re-open if needed.
