### ISSUE TITLE
Docker config for proxy points to incompatible traefik

### ISSUE THREAD

**Issue by carstenblt** [pipech/erpnext-docker-debian#72]
traefik:latest points to version 2, which does not work.

Can be fixed by using `traefik:1.7.16` in proxy.yml or updating the config files.

**Comment by pipech** [comment]
Thank you for pointing that out.

I'll change proxy.yml to traefik:v1.7.

**Comment by pipech** [comment]
https://github.com/pipech/erpnext-docker-debian/commit/415412ec54b5cb29ec58bed9f70123117a2fa237
