### ISSUE TITLE
MariaDB and Traefik

### ISSUE THREAD

**Issue by OnlineAlone** [pipech/erpnext-docker-debian#75]
Please advise on modifying Dockerfile to do the following,

- Escape installation of Traefik as TLS certifications are handled by Caddy server.
- Use system level MariaDB server.

On other note, please enhance WiKi pages with restore Docker Volume

Thanks

**Comment by pipech** [comment]
> Escape installation of Traefik as TLS certifications are handled by Caddy server.

Sorry, I never used Caddy can't help you there.


> Use system level MariaDB server.

- Don't start [db stack](https://github.com/pipech/erpnext-docker-debian/blob/master/production_setup/db.yml).
- Config [`common_site_config_docker.json`](https://github.com/pipech/erpnext-docker-debian/blob/master/production_setup/conf/frappe-docker-conf/common_site_config_docker.json) change `"db_host": "mariadb",` line to your db host.


> please enhance WiKi pages with restore Docker Volume

Noted.

**Comment by OnlineAlone** [comment]
Please advise about Traefik,

`/master/production_setup/db.yml`

```
      - "traefik.enable=False"
```
Is that setting is going to skip Traefik deployment by Docker? Thanks

**Comment by pipech** [comment]
> Is that setting is going to skip Traefik deployment by Docker? Thanks

If you don't want to use Traefik.

- Don't start proxy stack.
- Remove all Traefik related labels.
- Expose port 80 and 443 from frappe container.

**Comment by pipech** [comment]
Close due to inactivity, feel free to reopen if needed.
