### ISSUE TITLE
You are running Vue in development mode

### ISSUE THREAD

**Issue by garyritchie** [pipech/erpnext-docker-debian#79]
Browser console on several pages:

> You are running Vue in development mode.
> Make sure to turn on production mode when deploying for production.
> See more tips at https://vuejs.org/guide/deployment.html

Using image: `pipech/erpnext-docker-debian:v12-py3-latest`

**Comment by pipech** [comment]
Hi,

I just have time to look into this issues. If I'm not mistaken it is because frappe build process.

https://github.com/frappe/frappe/issues/9732
