### ISSUE TITLE
gettext missing from image

### ISSUE THREAD

**Issue by carstenblt** [pipech/erpnext-docker-debian#84]
Currently the image fails to start with

```
+ sudo -E /bin/bash -c 'envsubst '\''$NGINX_SERVER_NAME'\'' < nginx.temp > /etc/nginx/conf.d/default.conf'
/bin/bash: envsubst: command not found
```

Installing gettext fixes it.

**Comment by pipech** [comment]
Added.

https://github.com/pipech/erpnext-docker-debian/blob/8bf5f4d45d7c1b73b73dba49cc9ce27e66fc085b/Dockerfile#L174
