### ISSUE TITLE
Dockerfile is not working.

### ISSUE THREAD

**Issue by quantagonista** [pipech/erpnext-docker-debian#85]
Hi, pipech. Thanks a lot for your work on dockerizing ERPNext.
I am trying to deploy ERP using your Production Setup and that works fine.
Problem comes when I am trying to create my own frappe + erpnext  image like you did 
here - https://hub.docker.com/r/pipech/erpnext-docker-debian
Dockerfile posted there does not builds at all.
Could you please share Dockerfile for image docker `pipech/erpnext-docker-debian:v12-py3-latest`
Thanks a lot

**Comment by pipech** [comment]
Hi,

Dockerfile for image hosting in docker hub is the one in this repository. I think you just need to pass argument into docker build.

https://github.com/pipech/erpnext-docker-debian/blob/8bf5f4d45d7c1b73b73dba49cc9ce27e66fc085b/.travis/build_image.sh#L4-L8

So if you want to build `pipech/erpnext-docker-debian:v12-py3-latest` it would be.

```
docker build --no-cache \
   --build-arg pythonVersion="python3" \
   --build-arg appBranch="version-12" .
```

Building log for `pipech/erpnext-docker-debian:v12-py3-latest` is here. > [Travis](https://travis-ci.com/github/pipech/erpnext-docker-debian/jobs/298960141#L197)
