### ISSUE TITLE
Code not updating

### ISSUE THREAD

**Issue by khadijazaki2** [pipech/erpnext-docker-debian#86]
I have creating my custom image with my custom frappe and erpnext apps so I ran the bench update inside container it says that git updated but code does not gets updated.
and then if I run this command:
docker service update --force <stack_name>_frappe
it comes back to same state that I have to run git update again.
I think I am not understanding clearly what is the procedure of updating the code?

**Comment by pipech** [comment]
For custom app you have to update code by creating new image using Dockerfile then use that image to update docker service.

**Comment by khadijazaki2** [comment]
do I have to stop the docker swarm for this?

**Comment by pipech** [comment]
Hi, sorry for late reply.

Normally I would update image tag and take down the whole stack and start it with the same name but you could get away with updating image tag of frappe service.
