### ISSUE TITLE
Port for redis

### ISSUE THREAD

**Issue by lincogn** [pipech/erpnext-docker-debian#87]
Do you need to expose these three ports? It seems have error when the app start: 

"redis_cache": "redis://localhost:13000",
 "redis_queue": "redis://localhost:11000",
 "redis_socketio": "redis://localhost:12000",

**Comment by pipech** [comment]
Hi, could you post more detail on the error did you encounter such as when did it happen and error logs.

**Comment by lincogn** [comment]
If I use SSL (https://), it will have the following errors
Failed to load resource: net::ERR_CONNECTION_CLOSED
:32800/socket.io/?EIO=3&transport=polling&t=N4m0Iog net::ERR_CONNECTION_CLOSED

*For the 32800, originally it's 9000. As we use 32800 externally, we manually changed the desk.min.js to make it calling from 32800 for the service. I am not sure if this is appropriate too.

While if it's not using ssl, i.e. http://, it's working fine without any error.

**Comment by pipech** [comment]
What did you change from the original config?

**Comment by lincogn** [comment]
I haven't changed any setting. I just load the program and use https:// to browse the page. As I've already used the letsencrypt to encrypt the domain, I didn't set the ssl certification inside the container. Do you also run the program under ssl?

**Comment by pipech** [comment]
If you don't change any setting, how could you set socket.io port to 32800.

**Comment by lincogn** [comment]
We updated the port under sites/assets/js/desk.min.js from defined port to hard code as 32800.

**Comment by pipech** [comment]
Hi, really sorry for late reply but you should change config in 

production_setup/conf/frappe-docker-conf/common_site_config_docker.json 
```
"socketio_port": 9000,
```

production_setup/conf/frappe-docker-conf/nginx.temp 
```
upstream bench-socketio-server {
    server 127.0.0.1:9000 fail_timeout=0;
}
```

You might not need to change port on `sites/assets/js/desk.min.js`

Please let me know if it's work.

**Comment by lincogn** [comment]
Thanks for the reply. I've tested and there is no change. I've also change the same config in bench/config and it's the same result too. Do you have any other suggestion?

**Comment by ARAGATO** [comment]
Well, I do not know if the problem has something to do with each other.
On a fresh install of this rep using the developemnt in vscode environment when I just open the container and do a bench start it gives an error that those ports are in use and I cannot start the bench:

```
frappe@60079cdb3ca9:~/bench$ bench start
10:34:13 system           | redis_socketio.1 started (pid=738)
10:34:13 system           | redis_queue.1 started (pid=745)
10:34:13 system           | worker_default.1 started (pid=747)
10:34:13 system           | worker_short.1 started (pid=748)
10:34:13 redis_socketio.1 | 752:M 30 Apr 10:34:13.329 # Creating Server TCP listening socket 127.0.0.1:12000: bind: Address already in use
10:34:13 system           | redis_socketio.1 stopped (rc=1)
10:34:13 system           | socketio.1 started (pid=750)
10:34:13 redis_queue.1    | 756:M 30 Apr 10:34:13.331 # Creating Server TCP listening socket 127.0.0.1:11000: bind: Address already in use
10:34:13 system           | schedule.1 started (pid=746)
10:34:13 system           | redis_queue.1 stopped (rc=1)
10:34:13 system           | worker_long.1 started (pid=740)
10:34:13 system           | redis_cache.1 started (pid=749)
10:34:13 redis_cache.1    | 771:M 30 Apr 10:34:13.409 # Creating Server TCP listening socket 127.0.0.1:13000: bind: Address already in use
10:34:13 system           | redis_cache.1 stopped (rc=1)
10:34:13 system           | watch.1 started (pid=742)
10:34:13 system           | sending SIGTERM to worker_long.1 (pid 740)
10:34:13 system           | sending SIGTERM to watch.1 (pid 742)
10:34:13 system           | sending SIGTERM to schedule.1 (pid 746)
10:34:13 system           | sending SIGTERM to worker_default.1 (pid 747)
10:34:13 system           | sending SIGTERM to socketio.1 (pid 750)
10:34:13 system           | sending SIGTERM to worker_short.1 (pid 748)
10:34:13 system           | watch.1 stopped (rc=-15)
10:34:13 system           | worker_long.1 stopped (rc=-15)
10:34:13 system           | schedule.1 stopped (rc=-15)
10:34:13 system           | worker_default.1 stopped (rc=-15)
10:34:13 system           | worker_short.1 stopped (rc=-15)
10:34:13 system           | socketio.1 stopped (rc=-15)
```

**Comment by lincogn** [comment]
> Well, I do not know if the problem has something to do with each other.
> On a fresh install of this rep using the developemnt in vscode environment when I just open the container and do a bench start it gives an error that those ports are in use and I cannot start the bench:
> 
> ```
> frappe@60079cdb3ca9:~/bench$ bench start
> 10:34:13 system           | redis_socketio.1 started (pid=738)
> 10:34:13 system           | redis_queue.1 started (pid=745)
> 10:34:13 system           | worker_default.1 started (pid=747)
> 10:34:13 system           | worker_short.1 started (pid=748)
> 10:34:13 redis_socketio.1 | 752:M 30 Apr 10:34:13.329 # Creating Server TCP listening socket 127.0.0.1:12000: bind: Address already in use
> 10:34:13 system           | redis_socketio.1 stopped (rc=1)
> 10:34:13 system           | socketio.1 started (pid=750)
> 10:34:13 redis_queue.1    | 756:M 30 Apr 10:34:13.331 # Creating Server TCP listening socket 127.0.0.1:11000: bind: Address already in use
> 10:34:13 system           | schedule.1 started (pid=746)
> 10:34:13 system           | redis_queue.1 stopped (rc=1)
> 10:34:13 system           | worker_long.1 started (pid=740)
> 10:34:13 system           | redis_cache.1 started (pid=749)
> 10:34:13 redis_cache.1    | 771:M 30 Apr 10:34:13.409 # Creating Server TCP listening socket 127.0.0.1:13000: bind: Address already in use
> 10:34:13 system           | redis_cache.1 stopped (rc=1)
> 10:34:13 system           | watch.1 started (pid=742)
> 10:34:13 system           | sending SIGTERM to worker_long.1 (pid 740)
> 10:34:13 system           | sending SIGTERM to watch.1 (pid 742)
> 10:34:13 system           | sending SIGTERM to schedule.1 (pid 746)
> 10:34:13 system           | sending SIGTERM to worker_default.1 (pid 747)
> 10:34:13 system           | sending SIGTERM to socketio.1 (pid 750)
> 10:34:13 system           | sending SIGTERM to worker_short.1 (pid 748)
> 10:34:13 system           | watch.1 stopped (rc=-15)
> 10:34:13 system           | worker_long.1 stopped (rc=-15)
> 10:34:13 system           | schedule.1 stopped (rc=-15)
> 10:34:13 system           | worker_default.1 stopped (rc=-15)
> 10:34:13 system           | worker_short.1 stopped (rc=-15)
> 10:34:13 system           | socketio.1 stopped (rc=-15)
> ```

Shouldn't be. The docker can be started even redis and socket cannot be started.

I want to first tackle the socket under SSL and then to the redis. My problem now is when I set it to under SSL, the socket reports effort. I am pretty sure it's related to the socket port because by default inside the docker, it's in 9000 port. However, when it under the docker, the external port become different and it's required to do some setting to make the docker 1. Change the external socket link from 9000 to 32800 (in my case). 2. Set the socket accepting / converting / redirecting / matching the 32800 port to the internal 9000 port. The concept should be correct but I cannot figure out how to work this out.

**Comment by ARAGATO** [comment]
Sorry for not posting a reply earlier. I found out that bench was already started so ports were used already. A simple bench serve starts the webserver and that it works.

**Comment by lincogn** [comment]
> Sorry for not posting a reply earlier. I found out that bench was already started so ports were used already. A simple bench serve starts the webserver and that it works.

Yes it works. However, when you use it under SSL, the server will keep prompting error as I shared.
