### ISSUE TITLE
[QUESTION] Where is everything stored?

### ISSUE THREAD

**Issue by ARAGATO** [pipech/erpnext-docker-debian#92]
I love your work and want and I have been learning the last couple of days using docker and especially your package with erpnext-docker-debian/development_setup_vscode.

I am trying to figure out how to do a full backup of my current docker/erpnext environment. Let's say the container is open via vs code and I create a couple of new sites. I fill those sites with demo data. Those changes are all in the database and in the /bench/sites folder which is not mounted to the shared_dev folder. Also, there is no volume attached to the container besides the apps folder.
Question now is, where is everything stored? Inside the container? If so, how can I create a complete backup of the whole setup to migrate to another computer for example?

That would be highly appreciated.

**Comment by pipech** [comment]
Hi, ARAGATO

For development setup everything is stored in the container, if you want to migrate to another computer normally I would use git to pull all the commit and set it all up again but if you really want to save all site data you could use docker commit to commit container into image and set it up using that image.

But for production setup all necessary data will be stored on docker volumes then you could back up volumes using frank and migrate that to another computer.
