### ISSUE TITLE
[Warning] Aborted connection 10 to db

### ISSUE THREAD

**Issue by SuperJuke** [pipech/erpnext-docker-debian#93]
I installed NextERP using the Production Setup guide from this wiki:
https://github.com/pipech/erpnext-docker-debian/wiki/Production-Setup

The installation completed successfully using image "v12-py3-latest". I'm able to login to the desk but nothing seems to work. I tried adding an employee under the HRM module, typed in the information but nothing shows after I do this. Can some one help. Saw this(below) under the MariaDB log. Could this be why?

> 2020-05-08 22:22:33 10 [Warning] Aborted connection 10 to db: '_ef388772ccaafc09' user: '_ef388772ccaafc09' host: '10.0.2.4' (Got an error reading communication packets)

**Comment by tarundixitravi** [comment]
can you please share the solution, believing that you closed this thread after success
