### ISSUE TITLE
SSL configuration

### ISSUE THREAD

**Issue by abdulmutal** [pipech/erpnext-docker-debian#94]
Hi,
I am new to docker container and to the erpnext system as well. Can you please tell me how can i configure ssl and domain to your docker.

I have pull the image of erpnext from your dockerhub.

**Comment by pipech** [comment]
Sorry for late reply,

If you setting up production server you should follow this guide. SSL will be automatically config from traefik container.

https://github.com/pipech/erpnext-docker-debian/wiki/Production-Setup
