### ISSUE TITLE
FYI: Migration step missing from v12-py3-latest

### ISSUE THREAD

**Issue by garyritchie** [pipech/erpnext-docker-debian#96]
After a recent update of the stack I started to receive some errors, such as "Unknown column 'allocate_payment_based_on_payment_terms'" when trying to record a payment entry, for example.

Also getting: "Not found
The resource you are looking for is not available"
and in the browser console: `Failed to load resource: the server responded with a status of 404 () api/method/frappe.email.doctype.email_account.email_account.get_automatic_email_link:1`
on each desk page load.

I found the container id, exec'd inside and ran `bench migrate` and several migrations were performed. This allowed me to resume payment recording.

**Comment by carstenblt** [comment]
Tbh I would advise you to always do the migration steps manually. ERPNext is not rock stable, so migration can run into problems from time to time...
