### ISSUE TITLE
Running on Plesk

### ISSUE THREAD

**Issue by zayn008** [pipech/erpnext-docker-debian#97]
So I have managed to get it running on Plesk on the IP address, right now I have 2 issues:

1) Where do I map the volumes for data storage? Plesk asks for the 'container' and the 'host' I assume Container is the location within the container and host is the local storage where you want to map it. Otherwise a reboot will delete all the data

2) How do I secure with SSL?

**Comment by pipech** [comment]
Could you share how did you set-up on Plesk ?

**Comment by pipech** [comment]
Close due to inactivity.

**Comment by zayn008** [comment]
Sorry for not replying to this, I searched for the image, unticked automatic port mapping, opened the ports needed and mapped it to my URL... I can give you access if you'd like to see? It's just the volume mapping and SSH to run Bench commands that i need help with, everything else is excellent

**Comment by pipech** [comment]
For volume mapping you could use [Plesk Volume mapping](https://support.plesk.com/hc/en-us/articles/115001973253-How-to-map-volumes-in-Docker-on-Plesk-server-)

 - Destination field - the absolute path to a directory inside the container.
 - Source field - the absolute path to the directory on the server that should be mounted in the container

So for frappe container you should map
 - /home/frappe/bench/sites
 - /home/frappe/bench/logs
 - /var/lib/mysql

For SSL, you should be able to use be able to use SSL from plesk and proxy to forward incoming connection to ERPNext container

```Home > Domains > Apache & nginx Settings for [Domain name] > nginx settings```

```
location ^~/socket.io {
    proxy_pass http://0.0.0.0:8080;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Frappe-Site-Name $host;
    proxy_set_header Origin $scheme://$http_host;
    proxy_set_header Host $host;
}

location ~^/.* {
    proxy_pass http://0.0.0.0:8080;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}
```

Some thing like this

**Comment by zayn008** [comment]
Hi, thanks for your reply. I tried that for the volume mapping but it kept saying invalid login after so I had to remove it.
Is there a way I can stop having to use "sudo docker exec erpnext-docker-debian bench" and just do "bench" in SSH?

**Comment by pipech** [comment]
> i, thanks for your reply. I tried that for the volume mapping but it kept saying invalid login after so I had to remove it. I'm guessing its the MySQL bit

After mapping volume you might want to init new site



> Is there a way I can stop having to use "sudo docker exec erpnext-docker-debian bench" and just do "bench" in SSH?

I don't think there is, you could add sudoers to docker but it just remove sudo to the command.
https://docs.docker.com/engine/install/linux-postinstall/

**Comment by zayn008** [comment]
Excellent! I also found if I run `docker exec -t -i erpnext-docker-debian /bin/bash` I can just run bench and access the files within the container as if im not even using docker
